### ISSUE TITLE
blank visualization

### ISSUE THREAD

**Issue by liyanc** [facebookresearch/d3d-hoi#4]
Hello,

I followed the instruction for preprocessing the CAD models, which works as expected. But `visualization/visualize_data.py` renders only background images with empty object masks. An example is attached.

steps to reproduce:
`python ./d3d-hoi/visualization/visualize_data.py --data_folder ./d3dhoi_video_data/dishwasher/b001-0001 --cad_folder ./cad_sapien/Dishwasher`

![plot1](https://user-images.githubusercontent.com/25853995/137618168-5ab74d1b-c964-430e-b40d-287e458e8768.png)

**Comment by samxuxiang** [comment]
There are two steps involved. Read in the ground-truth annotation https://github.com/facebookresearch/d3d-hoi/blob/6419d36d39ccfc0dacb7753d8ae0820780290a87/visualization/visualize_data.py#L187 and then initialize the model https://github.com/facebookresearch/d3d-hoi/blob/6419d36d39ccfc0dacb7753d8ae0820780290a87/visualization/visualize_data.py#L102 Can you verify that the first step is working correctly? 
Since you have blank render of the object, I suspect  issue is with forward pass of the model at here https://github.com/facebookresearch/d3d-hoi/blob/6419d36d39ccfc0dacb7753d8ae0820780290a87/visualization/model.py#L79 More specifically, can you track down the value of variable `obj_verts` through out the forward pass? This is the vertex coord of the object and if it is too small or too far away things could just not show up. After adjusting all the ground-truth offset, rotation, orientation and etc, the final meshes are created in here https://github.com/facebookresearch/d3d-hoi/blob/6419d36d39ccfc0dacb7753d8ae0820780290a87/visualization/model.py#L113 
If `obj_verts` value is fine but output after this step is bad, then you should examine the pytorch3d camera model `vis_render` defined here https://github.com/facebookresearch/d3d-hoi/blob/6419d36d39ccfc0dacb7753d8ae0820780290a87/visualization/utils.py#L55
I hope this can help you track down the issue.
